# Generated by Django 2.2 on 2020-07-17 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fav_books_app', '0002_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='liked_books',
            new_name='user_who_liked',
        ),
    ]
